version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Shop
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
